### ISSUE TITLE
Provide a sprite instead of an actual texture for FILL?

### ISSUE THREAD

**Issue by awesomez** [Unity-Technologies/2d-spriteshape-samples#3]
So I have a grid full of smaller (9-slice) "tile" graphics that I want to use. They look something like this:

![tilea3](https://user-images.githubusercontent.com/41122894/42910072-c200f0d6-8aab-11e8-9e41-2c7185af86d3.png)

I'd like to "grab" the central "tile" slice (tile #5 in a 9-slice) in each group of 9-slices (because it's tileable in all 4 directions) and be able to add it as the spriteshape "fill" (instead of having to manually go crop each and every tile, make a new material, etc. etc.) The edges of the 9-slice groups I would use for the repeating borders and corners of a spriteshape, but the *center* of each "square" (9-slice) group is a tileable portion of the graphic because it tiles in all directions.

**Comment by venkify** [comment]
Fill part of the SpriteShape requires the Texture Wrap Mode to Repeat so UV generation is simplified and tessellation therefore is fast and simple. This can be problematic if Sprites are used especially if its a part of SpriteSheet or Atlas. The idea is to ensure SpriteShape is as fast as it can be so it can modifiable at runtime.
